services:
    dmzx.forumicons.listener:
        class: dmzx\forumicons\event\listener
        arguments:
            - '@template'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
